### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by naviji**

### CODE REVIEW

**Comment by biswaz** [comment]
Do we really need .coverage in .gitignore?

**Comment by naviji** [comment]
It was modified without me doing anything to it. 
The .gitignore already has .coverage.* 
Ignore if you think it's unnecessary.

**Comment by biswaz** [comment]
Can't ignore. Make another commit and add to this PR.
https://stackoverflow.com/questions/10147445/github-adding-commits-to-existing-pull-request

**Comment by naviji** [comment]
" Add more commits by pushing to the master branch on naveencode/invento18. "

**Review by biswaz — CHANGES_REQUESTED** [review]
Remove this commit from this PR

**Review by biswaz — COMMENTED** [review]
This will do

**Review by biswaz — APPROVED** [review]

**Pull request merged**
